package com.ezr.hoopfire.ui.home;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class HomeScreenDesign extends HorizontalLayout {
	protected Image hoopFireLogo;
	protected Button menuButton;
	protected CssLayout menu;
	protected Button home;
	protected Button nba;
	protected Button ncaaBasketball;
	protected Button about;
	protected Button admin;
	protected VerticalLayout contentLayout;

	public HomeScreenDesign() {
		Design.read(this);
	}
}
